// generated by github copilot

module tb;
    reg [63:0] arg0;
    wire [63:0] ret;
    reg go;
    reg clk;
    reg reset;
    wire done;

    _pulsar_Smain_q_q main(
        .arg0(arg0),
        .ret(ret),
        .go(go),
        .clk(clk),
        .reset(reset),
        .done(done)
    );

    always #1 clk = ~clk;

    initial begin
        arg0 = 64'h0;
        go = 1'b0;
        clk = 1'b0;
        reset = 1'b0;

        reset = 1'b1;
        #10;
        reset = 1'b0;
        #10;

        arg0 = 64'h123456789ABCDEF0;
        go = 1'b1;
        #10;

        for (int i = 0; i < 1000; i++) begin
            arg0[31:0] = $random;
            go = 1'b1;
            #10;
            while (!done) #10;
            if (ret !== arg0 + 1) begin
                $display("Test failed: expected %h, got %h", arg0 + 1, ret);
                $finish;
            end
            go = 1'b0;
            #10;
        end

        $display("Test passed");
        $finish;
    end
endmodule
