literal = ? literal value ?

prefix-op = ? prefix operator ?

infix-op = ? infix operator ?

primary-expr
    = literal
    | "(", expr, ")";

prefix-unary-expr
    = prefix-op, expr;

infix-binary-expr
    = expr, infix-op, expr;

postfix-binary-expr
    = expr, "[", expr, "]";

expr
    = primary-expr
    | prefix-unary-expr
    | infix-binary-expr
    | postfix-binary-expr;
